[package]
name = "bitread"
version = "0.1.1"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "bitread_macro",
]

[dependencies]
bitread_macro = { path = "bitread_macro" }
bitvec = "1.0.1"