push=true
publish=true
consolidate-commits=true
pre-release-commit-message="release: bitread and bitread_macro release"
tag=true
tag-prefix="{{crate_name}}"
tag-message="release {{version}}"
tag-name="{{prefix}}-v{{version}}"
